### ISSUE TITLE
Block Grinder and XP tanks unable to be upgraded

### ISSUE THREAD

**Issue by zulater** [LorgeN/CrazyWars-Issues#84] opened 2019-10-16 03:54 UTC
**Minecraft Username**
zulater

**What is this about?**
Block Grinder and XP Tanks upgrading

**To Reproduce**
Place block grinder or XP Tank and try to upgrade

**What happens?**
It does not upgrade ( I believe due to recent dupe glitch fix )

**What should happen?**
Should let you upgrade it

**Comment by LorgeN** [comment] 2019-10-24 08:38
Duplicate of https://github.com/LorgeN/CrazyWars-Issues/issues/97

**Closed** 2019-10-24 08:38 UTC
Labels: bug, dev-fixed
