### ISSUE TITLE
Quests completing before having required items

### ISSUE THREAD

**Issue by zulater** [LorgeN/CrazyWars-Issues#10] opened 2019-09-10 01:14 UTC
**Minecraft Username**
ParkourM4ster (zulater submitting)

**What is this about?**
NPC Quests

**To Reproduce**
Watch video, apparently going back and forth from /is to /mr will allow the quest to complete the gathering portion randomly then when you come back to /is it will auto hand it in without ever collecting it.

**What happens?**
Reward and tokens are granted without completing required quest

**What should happen?**
You should have to complete the gathering quest and hand it in before it will complete

**Screenshots/Videos**
https://www.youtube.com/watch?v=PRfKsbO15Qo&feature=youtu.be

**Additional context**
I (zulater) am unable to re-produce the issue yet.  I tried for about 10 minutes going back and forth /is /mr and tried each setting (go to island or go to bg) neither worked to reproduce the error.  May be a tough one to track down.

**Comment by LorgeN** [comment] 2019-09-10 13:03
Potentially fixed by https://github.com/LorgeN/CrazyWars/commit/18b2a040cc949fa9156b3d4466801bcfb3df2c61

**Comment by zulater** [comment] 2019-09-10 23:00
Happened today for ParkourM4ster  if you haven't applied the update then maybe ignore:

ok so i kinda trimmed it bad but at exactly 0:00 it says quest started 20x blazes in chat and on the side bar
i also included the quest completion to show that it wasnt a visual thing :
https://youtu.be/UmO0F7UTflQ

**Comment by LorgeN** [comment] 2019-09-10 23:09
Could potentially be caused by checking #isComplete before Objectives are loaded.

**Comment by FlameShine11** [comment] 2019-09-14 11:31
I just had this happen to me this morning.  Had a gold ore quests, completed gathering.  Put the ores in furnace for next part of quest and someone needed help in CP, after helping and /island (ended up in BG spawn).  I received the "rewards received" announcement.  Ores still in my furnace on island and never handed into the NPC in BG.

**Comment by LorgeN** [comment] 2019-09-14 13:33
I added some more stuff to hopefully fix this. Should be sorted next update, potentially.

**Closed** 2019-09-17 18:24 UTC
Labels: bug
